# Default values for cert-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cert-broker
  tag: latest
  pullPolicy: IfNotPresent

certbroker:
  namespace: "default"
  replicaWorkers: 4
  cleanupWorkers: 1
  controlClusterSecret:
  targetClusterSecret: "target-cluster"

certmanager:
  clusterissuer: "gardener-issuer"
  acmeChallengeType: "dns01"
  acmeDNS01Provider: "route53"
  updateIngress: "true"
  leaderElection: "true"