required = [
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^v1.0.6"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~v1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~v1.4.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  go-tests = true
