apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
    - "certmanager.k8s.io"
    resources:
    - "certificates"
    verbs:
    - "get" 
    - "list"
    - "watch"
  - apiGroups:
    - "extensions"
    resources:
    - "ingresses"
    verbs:
    - "get" 
    - "list"
    - "watch"
    - "update"
    - "delete"
  - apiGroups:
    - "events.k8s.io"
    resources:
    - "events"
    verbs:
    - "get"
    - "create"
    - "update"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get" 
    - "list"
    - "watch"
    - "delete"
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - "*" 
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}
subjects:
  - name: {{ .Chart.Name }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount